[package]
name = "token-gen"
version = "0.1.0"
authors = ["andrew"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
jsonwebtoken = "5"
serde_derive = "1"
serde = "1"
toml = "0.4.2"

[dependencies.yaml-rust]
git = "https://github.com/chyh1990/yaml-rust.git"
